spring.application.name=API-ejercicio
spring.datasource.url=jdbc:mysql://localhost:3307/ejercicio_bd
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.password=root
spring.datasource.username=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.sql.init.mode=always

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.defer-datasource-initialization=true

spring.web.locale=es

jwt.secret=f90f0aea6ed3ee6fb26e1be96bc01df00f69e30e522f3de1be80a49f7a6c0142
jwt.expiration=86400000
jwt.refresh-expiration=604800000
#springdoc.swagger-ui.path=/documentacion
